name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # Runs at 08h00 on Sunday
    - cron: '0 8 * * 0'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://feeds.feedburner.com/JonyPeixoto"
